server {
    listen 80;
    client_max_body_size 50M;
    client_body_buffer_size 50M;
    keepalive_timeout 5;
    server_name imp.local.boco.com;
    charset utf-8;
    gzip on;

    location ~* \.(asp|aspx|php|jsp|cgi|7z)$ {
        return 404;
    }
    location ~* \.map$ {
        return 404;
    }

    location ~* \.(js|css|eot|otf|ttf|woff|svg)$ {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
        add_header Access-Control-Allow-Headers Origin,X-Requested-With,Content-Type,Accept,Authorization,XCSRF-TOKEN,DNT,X-CustomHeader,Keep-Alive,User-Agent,If-Modified-Since,Cache-Control,Content-Range,Range;
    }

    location ~* VERSION$ {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
        add_header Access-Control-Allow-Headers Origin,X-Requested-With,Content-Type,Accept,Authorization,XCSRF-TOKEN,DNT,X-CustomHeader,Keep-Alive,User-Agent,If-Modified-Since,Cache-Control,Content-Range,Range;
    }

    location ^~ / {
        proxy_pass http://127.0.0.1:9002/;
        proxy_read_timeout 600;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;

        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
        add_header Access-Control-Allow-Headers Origin,X-Requested-With,Content-Type,Accept;
    }
}

server {
    listen 9002;
    client_max_body_size 50M;
    client_body_buffer_size 50M;
    keepalive_timeout 5;
    server_name 127.0.0.1;

    root /Users/jasonj/Documents/oss-imp-alarm/build;
    index index.html;

    try_files $uri $uri/ /index.html?/$request_uri;

    location = /index.html {
        add_header Cache-Control no-cache;
    }

    location / {
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "POST, GET, PUT, OPTIONS, DELETE";
            add_header Access-Control-Max-Age "3600";
            add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization, FOO";
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 200;
        }
    }

    error_page 404 403 /404.html;
}