export const activeAlarmColumn = [
    {
        name: '地市名称',
        field: 'region_name',
        alias: '地市名称',
        width: 120,
    },
    {
        name: '网元名称',
        field: 'eqp_label',
        alias: '网元名称',
        width: 120,
    },
    {
        name: '设备类型',
        field: 'eqp_object_class',
        alias: '设备类型',
        width: 120,
    },
    {
        name: '告警对象名称',
        field: 'ne_label',
        alias: '告警对象名称',
        width: 120,
    },
    {
        name: '告警对象设备类型',
        field: 'object_class',
        alias: '告警对象设备类型',
        width: 120,
    },
    {
        name: '网管告警级别',
        field: 'org_severity',
        alias: '网管告警级别',
        width: 120,
    },
    {
        name: '告警标题',
        field: 'title_text',
        alias: '告警标题',
        width: 120,
    },
    {
        name: '告警发生时间',
        field: 'event_time',
        alias: '告警发生时间',
        width: 120,
    },
    {
        name: '派单状态',
        field: 'send_status',
        alias: '派单状态',
        width: 120,
    },
    {
        name: '工单号',
        field: 'sheet_no',
        alias: '工单号',
        width: 120,
    },
    {
        name: '设备工程状态',
        field: 'resource_status',
        alias: '设备工程状态',
        width: 120,
    },
    {
        name: '工单状态',
        field: 'sheet_status',
        alias: '工单状态',
        width: 120,
    },
    {
        name: '告警工程状态',
        field: 'alarm_resource_status',
        alias: '告警工程状态',
        width: 120,
    },
];
export const confirmAlarmColumn = [
    {
        name: '地市名称',
        field: 'region_name',
        alias: '地市名称',
        width: 120,
    },
    {
        name: '网元名称',
        field: 'eqp_label',
        alias: '网元名称',
        width: 120,
    },
    {
        name: '设备类型',
        field: 'eqp_object_class',
        alias: '设备类型',
        width: 120,
    },
    {
        name: '告警对象名称',
        field: 'ne_label',
        alias: '告警对象名称',
        width: 120,
    },
    {
        name: '告警对象设备类型',
        field: 'object_class',
        alias: '告警对象设备类型',
        width: 120,
    },
    {
        name: '网管告警级别',
        field: 'org_severity',
        alias: '网管告警级别',
        width: 120,
    },
    {
        name: '告警标题',
        field: 'title_text',
        alias: '告警标题',
        width: 120,
    },
    {
        name: '告警发生时间',
        field: 'event_time',
        alias: '告警发生时间',
        width: 120,
    },
    {
        name: '告警确认状态',
        field: 'ack_flag',
        alias: '告警确认状态',
        width: 120,
    },
    {
        name: '派单状态',
        field: 'send_status',
        alias: '派单状态',
        width: 120,
    },
    {
        name: '工单号',
        field: 'sheet_no',
        alias: '工单号',
        width: 120,
    },
    {
        name: '设备工程状态',
        field: 'resource_status',
        alias: '设备工程状态',
        width: 120,
    },
    {
        name: '工单状态',
        field: 'sheet_status',
        alias: '工单状态',
        width: 120,
    },
    {
        name: '告警工程状态',
        field: 'alarm_resource_status',
        alias: '告警工程状态',
        width: 120,
    },
];
export const clearAlarmColumn = [
    {
        name: '地市名称',
        field: 'region_name',
        alias: '地市名称',
        width: 120,
    },
    {
        name: '网元名称',
        field: 'eqp_label',
        alias: '网元名称',
        width: 120,
    },
    {
        name: '设备类型',
        field: 'eqp_object_class',
        alias: '设备类型',
        width: 120,
    },
    {
        name: '告警对象名称',
        field: 'ne_label',
        alias: '告警对象名称',
        width: 120,
    },
    {
        name: '告警对象设备类型',
        field: 'object_class',
        alias: '告警对象设备类型',
        width: 120,
    },
    {
        name: '网管告警级别',
        field: 'org_severity',
        alias: '网管告警级别',
        width: 120,
    },
    {
        name: '告警标题',
        field: 'title_text',
        alias: '告警标题',
        width: 120,
    },
    {
        name: '告警发生时间',
        field: 'event_time',
        alias: '告警发生时间',
        width: 120,
    },
    {
        name: '告警清除状态',
        field: 'active_status',
        alias: '告警清除状态',
        width: 120,
    },
    {
        name: '告警清除时间',
        field: 'cancel_time',
        alias: '告警清除时间',
        width: 120,
    },
    {
        name: '派单状态',
        field: 'send_status',
        alias: '派单状态',
        width: 120,
    },
    {
        name: '工单号',
        field: 'sheet_no',
        alias: '工单号',
        width: 120,
    },
    {
        name: '设备工程状态',
        field: 'resource_status',
        alias: '设备工程状态',
        width: 120,
    },
    {
        name: '工单状态',
        field: 'sheet_status',
        alias: '工单状态',
        width: 120,
    },
    {
        name: '告警工程状态',
        field: 'alarm_resource_status',
        alias: '告警工程状态',
        width: 120,
    },
];

export const cleardAckAlarmColumn = [
    {
        name: '地市名称',
        field: 'region_name',
        alias: '地市名称',
        width: 120,
    },
    {
        name: '网元名称',
        field: 'eqp_label',
        alias: '网元名称',
        width: 120,
    },
    {
        name: '设备类型',
        field: 'eqp_object_class',
        alias: '设备类型',
        width: 120,
    },
    {
        name: '告警对象名称',
        field: 'ne_label',
        alias: '告警对象名称',
        width: 120,
    },
    {
        name: '告警对象设备类型',
        field: 'object_class',
        alias: '告警对象设备类型',
        width: 120,
    },
    {
        name: '网管告警级别',
        field: 'org_severity',
        alias: '网管告警级别',
        width: 120,
    },
    {
        name: '告警标题',
        field: 'title_text',
        alias: '告警标题',
        width: 120,
    },
    {
        name: '告警发生时间',
        field: 'event_time',
        alias: '告警发生时间',
        width: 120,
    },
    {
        name: '告警清除状态',
        field: 'active_status',
        alias: '告警清除状态',
        width: 120,
    },
    {
        name: '告警清除时间',
        field: 'cancel_time',
        alias: '告警清除时间',
        width: 120,
    },
    {
        name: '派单状态',
        field: 'send_status',
        alias: '派单状态',
        width: 120,
    },
    {
        name: '工单号',
        field: 'sheet_no',
        alias: '工单号',
        width: 120,
    },
    {
        name: '设备工程状态',
        field: 'resource_status',
        alias: '设备工程状态',
        width: 120,
    },
    {
        name: '工单状态',
        field: 'sheet_status',
        alias: '工单状态',
        width: 120,
    },
    {
        name: '告警工程状态',
        field: 'alarm_resource_status',
        alias: '告警工程状态',
        width: 120,
    },
];
export const queryAlarmColumnDefault = [
    {
        name: '地市名称',
        field: 'region_name',
        alias: '地市名称',
        width: 120,
    },
    {
        name: '网元名称',
        field: 'eqp_label',
        alias: '网元名称',
        width: 120,
    },
    {
        name: '设备类型',
        field: 'eqp_object_class',
        alias: '设备类型',
        width: 120,
    },
    {
        name: '告警对象名称',
        field: 'ne_label',
        alias: '告警对象名称',
        width: 120,
    },
    {
        name: '告警对象设备类型',
        field: 'object_class',
        alias: '告警对象设备类型',
        width: 120,
    },
    {
        name: '网管告警级别',
        field: 'org_severity',
        alias: '网管告警级别',
        width: 120,
    },
    {
        name: '告警标题',
        field: 'title_text',
        alias: '告警标题',
        width: 120,
    },
    {
        name: '告警发生时间',
        field: 'event_time',
        alias: '告警发生时间',
        width: 120,
    },
    {
        name: '派单状态',
        field: 'send_status',
        alias: '派单状态',
        width: 120,
    },
    {
        name: '告警清除状态',
        field: 'active_status',
        alias: '告警清除状态',
        width: 120,
    },
    {
        name: '告警清除时间',
        field: 'cancel_time',
        alias: '告警清除时间',
        width: 120,
    },
    {
        name: '工单号',
        field: 'sheet_no',
        alias: '工单号',
        width: 120,
    },
    {
        name: '设备工程状态',
        field: 'resource_status',
        alias: '设备工程状态',
        width: 120,
    },
    {
        name: '工单状态',
        field: 'sheet_status',
        alias: '工单状态',
        width: 120,
    },
    {
        name: '告警工程状态',
        field: 'alarm_resource_status',
        alias: '告警工程状态',
        width: 120,
    },
];
