// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `cloud_view_base.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function (module, require, exports) {
  if (window.com) {
    return;
  }
  var Ice = require('./Ice.min.js').Ice;
  var __M = Ice.__M;
  var Slice = Ice.Slice;
  var com = __M.module('com');
  com.boco = __M.module('com.boco');
  com.boco.view = __M.module('com.boco.view');
  com.boco.view.slice = __M.module('com.boco.view.slice');
  com.boco.view.slice.generated = __M.module('com.boco.view.slice.generated');
  com.boco.view.slice.generated.model = __M.module('com.boco.view.slice.generated.model');

  /**
   * 创建会话
   **/
  com.boco.view.slice.generated.model.CreateSessionRequest = Slice.defineObject(function (clientUserName, clientToken, clientDesc, subscribeBusiness, subscribeInfoJSON) {
    Ice.Object.call(this);
    this.clientUserName = clientUserName !== undefined ? clientUserName : '';
    this.clientToken = clientToken !== undefined ? clientToken : '';
    this.clientDesc = clientDesc !== undefined ? clientDesc : '';
    this.subscribeBusiness = subscribeBusiness !== undefined ? subscribeBusiness : '';
    this.subscribeInfoJSON = subscribeInfoJSON !== undefined ? subscribeInfoJSON : '';
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::CreateSessionRequest'], -1, function (__os) {
    __os.writeString(this.clientUserName);
    __os.writeString(this.clientToken);
    __os.writeString(this.clientDesc);
    __os.writeString(this.subscribeBusiness);
    __os.writeString(this.subscribeInfoJSON);
  }, function (__is) {
    this.clientUserName = __is.readString();
    this.clientToken = __is.readString();
    this.clientDesc = __is.readString();
    this.subscribeBusiness = __is.readString();
    this.subscribeInfoJSON = __is.readString();
  }, false);
  com.boco.view.slice.generated.model.CreateSessionRequestPrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.CreateSessionRequest.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.CreateSessionRequest, com.boco.view.slice.generated.model.CreateSessionRequestPrx);

  /**
   * 创建会话结果
   **/
  com.boco.view.slice.generated.model.CreateSessionResponse = Slice.defineObject(function (clientUserName, clientSessionId, dealDesc, subscribeProperties) {
    Ice.Object.call(this);
    this.clientUserName = clientUserName !== undefined ? clientUserName : '';
    this.clientSessionId = clientSessionId !== undefined ? clientSessionId : '';
    this.dealDesc = dealDesc !== undefined ? dealDesc : '';
    this.subscribeProperties = subscribeProperties !== undefined ? subscribeProperties : '';
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::CreateSessionResponse'], -1, function (__os) {
    __os.writeString(this.clientUserName);
    __os.writeString(this.clientSessionId);
    __os.writeString(this.dealDesc);
    __os.writeString(this.subscribeProperties);
  }, function (__is) {
    this.clientUserName = __is.readString();
    this.clientSessionId = __is.readString();
    this.dealDesc = __is.readString();
    this.subscribeProperties = __is.readString();
  }, false);
  com.boco.view.slice.generated.model.CreateSessionResponsePrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.CreateSessionResponse.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.CreateSessionResponse, com.boco.view.slice.generated.model.CreateSessionResponsePrx);

  /**
   * 关闭会话结果
   **/
  com.boco.view.slice.generated.model.CloseSessionResponse = Slice.defineObject(function (clientSessionId, clientOnlineTimeSecond, dealDesc) {
    Ice.Object.call(this);
    this.clientSessionId = clientSessionId !== undefined ? clientSessionId : '';
    this.clientOnlineTimeSecond = clientOnlineTimeSecond !== undefined ? clientOnlineTimeSecond : 0;
    this.dealDesc = dealDesc !== undefined ? dealDesc : '';
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::CloseSessionResponse'], -1, function (__os) {
    __os.writeString(this.clientSessionId);
    __os.writeLong(this.clientOnlineTimeSecond);
    __os.writeString(this.dealDesc);
  }, function (__is) {
    this.clientSessionId = __is.readString();
    this.clientOnlineTimeSecond = __is.readLong();
    this.dealDesc = __is.readString();
  }, false);
  com.boco.view.slice.generated.model.CloseSessionResponsePrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.CloseSessionResponse.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.CloseSessionResponse, com.boco.view.slice.generated.model.CloseSessionResponsePrx);

  /**
   * 通用接口模型,请求模型
   **/
  com.boco.view.slice.generated.model.RequestJSONMessage = Slice.defineObject(function (requestMethodName, clientRequestTimeMS, clientSessionId, requestDataJSON) {
    Ice.Object.call(this);
    this.requestMethodName = requestMethodName !== undefined ? requestMethodName : '';
    this.clientRequestTimeMS = clientRequestTimeMS !== undefined ? clientRequestTimeMS : 0;
    this.clientSessionId = clientSessionId !== undefined ? clientSessionId : '';
    this.requestDataJSON = requestDataJSON !== undefined ? requestDataJSON : '';
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::RequestJSONMessage'], -1, function (__os) {
    __os.writeString(this.requestMethodName);
    __os.writeLong(this.clientRequestTimeMS);
    __os.writeString(this.clientSessionId);
    __os.writeString(this.requestDataJSON);
  }, function (__is) {
    this.requestMethodName = __is.readString();
    this.clientRequestTimeMS = __is.readLong();
    this.clientSessionId = __is.readString();
    this.requestDataJSON = __is.readString();
  }, false);
  com.boco.view.slice.generated.model.RequestJSONMessagePrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.RequestJSONMessage.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.RequestJSONMessage, com.boco.view.slice.generated.model.RequestJSONMessagePrx);

  /**
   * 通用接口模型,请求模型
   **/
  com.boco.view.slice.generated.model.RequestWithRegistJSONMessage = Slice.defineObject(function (requestMethodName, clientRequestTimeMS, clientSessionId, requestDataJSON, createSessionRequest) {
    Ice.Object.call(this);
    this.requestMethodName = requestMethodName !== undefined ? requestMethodName : '';
    this.clientRequestTimeMS = clientRequestTimeMS !== undefined ? clientRequestTimeMS : 0;
    this.clientSessionId = clientSessionId !== undefined ? clientSessionId : '';
    this.requestDataJSON = requestDataJSON !== undefined ? requestDataJSON : '';
    this.createSessionRequest = createSessionRequest !== undefined ? createSessionRequest : null;
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::RequestWithRegistJSONMessage'], -1, function (__os) {
    __os.writeString(this.requestMethodName);
    __os.writeLong(this.clientRequestTimeMS);
    __os.writeString(this.clientSessionId);
    __os.writeString(this.requestDataJSON);
    __os.writeObject(this.createSessionRequest);
  }, function (__is) {
    var self = this;
    this.requestMethodName = __is.readString();
    this.clientRequestTimeMS = __is.readLong();
    this.clientSessionId = __is.readString();
    this.requestDataJSON = __is.readString();
    __is.readObject(function (__o) {
      self.createSessionRequest = __o;
    }, com.boco.view.slice.generated.model.CreateSessionRequest);
  }, false);
  com.boco.view.slice.generated.model.RequestWithRegistJSONMessagePrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.RequestWithRegistJSONMessage.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.RequestWithRegistJSONMessage, com.boco.view.slice.generated.model.RequestWithRegistJSONMessagePrx);

  /**
   * 通用接口模型,返回数据模型
   **/
  com.boco.view.slice.generated.model.ResponseJSONMessage = Slice.defineObject(function (clientSessionId, clientRequestTimeMS, requestMethodName, responseDataJSON, serverDealTimeMS) {
    Ice.Object.call(this);
    this.clientSessionId = clientSessionId !== undefined ? clientSessionId : '';
    this.clientRequestTimeMS = clientRequestTimeMS !== undefined ? clientRequestTimeMS : 0;
    this.requestMethodName = requestMethodName !== undefined ? requestMethodName : '';
    this.responseDataJSON = responseDataJSON !== undefined ? responseDataJSON : '';
    this.serverDealTimeMS = serverDealTimeMS !== undefined ? serverDealTimeMS : 0;
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::ResponseJSONMessage'], -1, function (__os) {
    __os.writeString(this.clientSessionId);
    __os.writeLong(this.clientRequestTimeMS);
    __os.writeString(this.requestMethodName);
    __os.writeString(this.responseDataJSON);
    __os.writeLong(this.serverDealTimeMS);
  }, function (__is) {
    this.clientSessionId = __is.readString();
    this.clientRequestTimeMS = __is.readLong();
    this.requestMethodName = __is.readString();
    this.responseDataJSON = __is.readString();
    this.serverDealTimeMS = __is.readLong();
  }, false);
  com.boco.view.slice.generated.model.ResponseJSONMessagePrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.ResponseJSONMessage.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.ResponseJSONMessage, com.boco.view.slice.generated.model.ResponseJSONMessagePrx);

  /**
   * 服务的基本信息
   **/
  com.boco.view.slice.generated.model.ViewServiceInfo = Slice.defineObject(function (serviceName, serviceAddress) {
    Ice.Object.call(this);
    this.serviceName = serviceName !== undefined ? serviceName : '';
    this.serviceAddress = serviceAddress !== undefined ? serviceAddress : '';
  }, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::model::ViewServiceInfo'], -1, function (__os) {
    __os.writeString(this.serviceName);
    __os.writeString(this.serviceAddress);
  }, function (__is) {
    this.serviceName = __is.readString();
    this.serviceAddress = __is.readString();
  }, false);
  com.boco.view.slice.generated.model.ViewServiceInfoPrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.model.ViewServiceInfo.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.model.ViewServiceInfo, com.boco.view.slice.generated.model.ViewServiceInfoPrx);

  /**
   * Ice服务统一抛出的服务异常，客户段通过判断错误代码来进行异常处理
   **/
  com.boco.view.slice.generated.model.ViewServiceException = Slice.defineUserException(function (code, reason, info, _cause) {
    Ice.UserException.call(this, _cause);
    this.code = code !== undefined ? code : '';
    this.reason = reason !== undefined ? reason : '';
    this.info = info !== undefined ? info : null;
  }, Ice.UserException, 'com::boco::view::slice::generated::model::ViewServiceException', function (__os) {
    __os.writeString(this.code);
    __os.writeString(this.reason);
    __os.writeObject(this.info);
  }, function (__is) {
    var self = this;
    this.code = __is.readString();
    this.reason = __is.readString();
    __is.readObject(function (__o) {
      self.info = __o;
    }, com.boco.view.slice.generated.model.ViewServiceInfo);
  }, false, true);
  com.boco.view.slice.generated.services = __M.module('com.boco.view.slice.generated.services');
  com.boco.view.slice.generated.services.IViewService = Slice.defineObject(undefined, Ice.Object, undefined, 1, ['::Ice::Object', '::com::boco::view::slice::generated::services::IViewService'], -1, undefined, undefined, false);
  com.boco.view.slice.generated.services.IViewServicePrx = Slice.defineProxy(Ice.ObjectPrx, com.boco.view.slice.generated.services.IViewService.ice_staticId, undefined);
  Slice.defineOperations(com.boco.view.slice.generated.services.IViewService, com.boco.view.slice.generated.services.IViewServicePrx, {
    createSessionBySync: [,,,,, ['com.boco.view.slice.generated.model.CreateSessionResponse', true], [['com.boco.view.slice.generated.model.CreateSessionRequest', true]],, [com.boco.view.slice.generated.model.ViewServiceException], true, true],
    createSession: [,,, 1,, ['com.boco.view.slice.generated.model.CreateSessionResponse', true], [['com.boco.view.slice.generated.model.CreateSessionRequest', true]],, [com.boco.view.slice.generated.model.ViewServiceException], true, true],
    executeMethodWithSession: [,,, 1,, ['com.boco.view.slice.generated.model.ResponseJSONMessage', true], [['com.boco.view.slice.generated.model.RequestJSONMessage', true]],, [com.boco.view.slice.generated.model.ViewServiceException], true, true],
    executeMethodWithCreateSession: [,,, 1,, ['com.boco.view.slice.generated.model.ResponseJSONMessage', true], [['com.boco.view.slice.generated.model.RequestWithRegistJSONMessage', true]],, [com.boco.view.slice.generated.model.ViewServiceException], true, true],
    executeMethod: [,,, 1,, ['com.boco.view.slice.generated.model.ResponseJSONMessage', true], [['com.boco.view.slice.generated.model.RequestJSONMessage', true]],, [com.boco.view.slice.generated.model.ViewServiceException], true, true],
    closeSession: [,,, 1,, ['com.boco.view.slice.generated.model.CloseSessionResponse', true], [[7], [7]],, [com.boco.view.slice.generated.model.ViewServiceException],, true],
    closeSessionBySync: [,,,,,, [[7], [7]],, [com.boco.view.slice.generated.model.ViewServiceException],,]
  });
  exports.com = com;
})(typeof global !== 'undefined' && typeof global.process !== 'undefined' ? module : undefined, typeof global !== 'undefined' && typeof global.process !== 'undefined' ? require : window.Ice.__require, typeof global !== 'undefined' && typeof global.process !== 'undefined' ? exports : window);