import constants from '@Common/services/constants';

const Tabs = [
    {
        tab: '通用查询',
        key: '1',
        queryType: 'alarmField',
        // menuOptions: ['add'],
        commonColumns: [
            'event_time',
            'active_status',
            'province_region_city',
            'network_type_top',
            'network_type',
            'vendor_id',
            'eqp_object_class',
            'eqp_label',
            'object_class',
            'ne_label',
            'org_severity',
            'extra_id3',
            'alarm_title_text',
            'standard_alarm_id',
            'alarm_resource_status',
            'send_status',
            'ack_flag',
            'is_undistributed_send_status',
            'alarm_origin',
            'sheet_status',
            'sheet_no',
            'gcss_client_name',
            'circuit_no',
            'gcss_client_level',
            'gcss_service_level',
            'interrupt_circuit_state',
            'alarm_abnormal_type',
        ],
        config: {
            search_span: {
                sm: {
                    with: 1400,
                    span: 8,
                },
                default: 6,
            },
            search_colSize: 1,
        },
    },
    {
        tab: '按过滤器查询',
        key: '2',
        queryType: 'filterId',
        columns: [
            {
                key: 'event_time',
                dataIndex: 'event_time',
                title: '告警发生时间',
                valueType: 'dateTimeRange',
                defaultValue: {
                    value: ['yesterday', 'today'],
                },
            },

            {
                key: 'filter_type',
                dataIndex: 'filter_type',
                title: '过滤方式',
                valueType: 'enumeration',
                // fieldSql: 'alarmSearch_selectFilterType',
                fieldEnum: [
                    { key: 'myFilters', value: '我的过滤器' },
                    { key: 'allFilters', value: '全部过滤器' },
                    // { key: 'ruleFitlers', value: '派单规则' },
                ],
                defaultValue: {
                    value: 'myFilters',
                },
            },
            // 此处 没有数据源，应该是特殊查询
            {
                key: 'filter_id',
                dataIndex: 'filter_id',
                title: '过滤器名称',
                valueType: 'enumeration',
                enumType: 'search',
                filterType: 'myFilters',
                fieldSearch: true,
                // fieldSql: '',
                // defaultValue: {
                //     value: 1,
                // },
            },
            {
                key: 'active_status',
                dataIndex: 'active_status',
                title: '告警状态',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldSql: 'alarmSearch_selectAlarmState',
                type: 68,
            },
            // {
            //     key: 'is_undistributed_send_status',
            //     dataIndex: '',
            //     title: '是否派单告警',
            //     valueType: 'enumeration',
            //     fieldPlaceholder: '是',
            //     // fieldSql: 'alarmSearch_selectIsUndistributedSendStatus',
            //     fieldEnum: [
            //         { key: -1, value: '是' },
            //         { key: 0, value: '否' },
            //     ],
            // },
            {
                key: 'send_status',
                dataIndex: 'send_status',
                title: '派单状态',
                valueType: 'enumeration',
                fieldSearch: true,
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectSendStatus',
                type: 52,
            },
            // {
            //     key: 'alarm_origin',
            //     dataIndex: 'alarm_origin',
            //     title: '关联查询',
            //     valueType: 'enumeration',
            //     fieldSearch: true,
            //     fieldSql: 'alarmSearch_selectAlarmOrigin',
            //     defaultValue: {
            //         value: '0',
            //     },
            // },
        ],
        config: {
            search_span: {
                sm: {
                    with: 1400,
                    span: 8,
                },
                default: 6,
            },
            // search_defaultCollapsed: false,
        },
    },
    {
        tab: '按唯一标识查询',
        key: '3',
        queryType: 'fp',
        columns: [
            {
                key: 'event_time',
                dataIndex: 'event_time',
                title: '告警发生时间',
                valueType: 'dateTimeRange',
                // hideInTable: true,
                defaultValue: {
                    value: ['yesterday', 'today'],
                },
            },
            // todo proTable title过长支持隐藏
            {
                key: 'nms_alarm_id',
                dataIndex: 'nms_alarm_id',
                title: '厂家唯一标识',
                fieldPlaceholder: '请输入厂家原始告警唯一标识',
                valueType: 'text',
            },
            {
                key: 'omc_alarm_id',
                dataIndex: 'omc_alarm_id',
                title: '原始流水号',
                fieldPlaceholder: '请输入原始告警流水号',
                valueType: 'text',
            },
            {
                key: 'fp0',
                dataIndex: 'fp0',
                title: 'fp0',
                valueType: 'text',
                // showOperator: true,
                // operatorKeys: ['eq', 'like'],
            },
            {
                key: 'fp1',
                dataIndex: 'fp1',
                title: 'fp1',
                valueType: 'text',
                // showOperator: true,
                // operatorKeys: ['eq', 'like'],
            },
            {
                key: 'fp2',
                dataIndex: 'fp2',
                title: 'fp2',
                valueType: 'text',
                // showOperator: true,
                // operatorKeys: ['eq', 'like'],
            },
            {
                key: 'fp3',
                dataIndex: 'fp3',
                title: 'fp3',
                valueType: 'text',
                // showOperator: true,
                // operatorKeys: ['eq', 'like'],
            },
        ],
        config: {
            search_span: {
                sm: {
                    with: 1400,
                    span: 8,
                },
                default: 6,
            },
        },
    },
];
const customQuery = {
    search_span: {
        sm: {
            with: 1400,
            span: 8,
        },
        default: 6,
    },
};
const Tabs_unicom = [
    {
        tab: '通用查询',
        key: '1',
        queryType: 'alarmField',
        columns: [
            {
                key: 'professional_type',
                dataIndex: 'professional_type',
                title: '专业',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // hideInTable: true,
                // fieldSql: 'alarmSearch_selectProfessionalType'
                type: 23,
            },
            {
                key: 'active_status',
                dataIndex: 'active_status',
                title: '告警状态',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldSql: 'alarmSearch_selectAlarmState',
                type: 68,
            },
            {
                key: 'province_region_city',
                dataIndex: 'province_region_city',
                title: '省市区',
                valueType: 'cascader',
                fieldSql: 'alarmSearch_selectProvinceRegionCity',
            },
            {
                key: 'event_time',
                dataIndex: 'event_time',
                title: '时间范围',
                valueType: 'dateTimeRange',
                defaultValue: {
                    value: ['yesterday', 'tonight'],
                },
            },
            {
                key: 'eqp_object_class',
                dataIndex: 'eqp_object_class',
                title: '设备类型',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // fieldSql: 'alarmSearch_selectEqpObjectClass'
                type: 9,
            },
            {
                key: 'vendor_id',
                dataIndex: 'vendor_id',
                title: '厂家',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // fieldSearch: true,
                fieldSql: 'alarmSearch_selectVendorId',
                type: 4,
            },
            {
                key: 'eqp_label',
                dataIndex: 'eqp_label',
                title: '网元名称',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'object_class',
                dataIndex: 'object_class',
                title: '告警对象类型',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectObjectClass',
                type: 18,
            },
            {
                key: 'ne_label',
                dataIndex: 'ne_label',
                title: '告警对象名称',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'org_severity',
                dataIndex: 'org_severity',
                title: '网管告警级别',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectOrgSeverity',
                // fieldEnum: [
                //     { key: 1, value: '一级告警' },
                //     { key: 2, value: '二级告警' },
                //     { key: 3, value: '三级告警' },
                //     { key: 4, value: '四级告警' },
                //     { key: 5, value: '正常' },
                // ],
                // defaultValue: {
                //     value: [1, 2],
                // },
                type: 33,
            },
            {
                key: 'alarm_resource_status',
                dataIndex: 'alarm_resource_status',
                title: '工程状态',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectAlarmResourceStatus',
                type: 14,
            },

            {
                // dataIndex: 'alarm_title',
                key: 'alarm_title_text',
                dataIndex: 'alarm_title_text',
                title: '告警标题',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'standard_alarm_id',
                dataIndex: 'standard_alarm_id',
                title: '网管告警ID',
                valueType: 'text',
                operatorKeys: ['eq', 'ne'],
                showOperator: true,
                defaultValue: {
                    operator: 'eq',
                },
            },
            // {
            //     key: 'alarm_origin',
            //     dataIndex: 'alarm_origin',
            //     title: '关联查询',
            //     valueType: 'enumeration',
            //     fieldSearch: true,
            //     fieldSql: 'alarmSearch_selectAlarmOrigin',
            //     defaultValue: {
            //         value: 0,
            //     },
            // },
            {
                key: 'ack_flag',
                dataIndex: 'ack_flag',
                title: '确认状态',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectAckFlag',
                type: 64,
            },
            {
                key: 'is_undistributed_send_status',
                dataIndex: 'is_undistributed_send_status',
                title: '是否派单告警',
                valueType: 'enumeration',
                // fieldSql: 'alarmSearch_selectIsUndistributedSendStatus',
                fieldEnum: [
                    { key: -1, value: '是' },
                    { key: 0, value: '否' },
                ],
            },
            // {
            //     key: 'sheet_type',
            //     dataIndex: 'sheet_type',
            //     title: '工单类型',
            //     valueType: 'enumeration',
            //     // fieldMode: 'multiple',
            //     fieldSql: ' ',
            //     type: 230,
            //     defaultValue: {
            //         value: 1,
            //     },
            //     allowClear: false,
            // },
            // {
            //     key: 'send_status',
            //     dataIndex: 'send_status',
            //     title: '派单状态',
            //     valueType: 'enumeration',
            //     fieldMode: 'multiple',
            //     fieldSql: 'alarmSearch_selectSendStatus',
            //     type: 52,
            // },
            // {
            //     key: 'new_send_status',
            //     dataIndex: 'new_send_status',
            //     title: '派单状态',
            //     valueType: 'enumeration',
            //     fieldMode: 'multiple',
            //     fieldSql: ' ',
            //     type: 52,
            //     // 默认值
            //     // fieldValue: 'send_status',
            //     // fieldEnum: [
            //     //     { value: 'send_status', label: '故障单', type: 52 },
            //     //     { value: 'supv_send_status', label: '督办单', type: 424 },
            //     //     { value: 'subway_send_status', label: '高铁单', type: 367 },
            //     // ],
            // },
            {
                key: 'new_send_status',
                dataIndex: 'new_send_status',
                title: '派单状态',
                valueType: 'newEnumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectSendStatus',
                type: 52,
                // 默认值
                fieldValue: 'send_status',
                fieldEnum: [
                    { value: 'send_status', label: '故障单', type: 52 },
                    { value: 'supv_send_status', label: '督办单', type: 424 },
                    { value: 'subway_send_status', label: '高铁单', type: 367 },
                ],
            },
            // {
            //     key: 'subway_send_status',
            //     dataIndex: 'subway_send_status',
            //     title: '高铁派单状态',
            //     valueType: 'enumeration',
            //     fieldMode: 'multiple',
            //     fieldSql: 'alarmSearch_selectSendStatus',
            //     type: 367,
            // },
            // {
            //     key: 'sheet_status',
            //     dataIndex: 'sheet_status',
            //     title: '工单状态',
            //     valueType: 'enumeration',
            //     fieldMode: 'multiple',
            //     fieldSql: 'alarmSearch_selectSheetStatus',
            //     type: 55,
            // },
            // {
            //     key: 'new_sheet_status',
            //     dataIndex: 'new_sheet_status',
            //     title: '工单状态',
            //     valueType: 'enumeration',
            //     fieldMode: 'multiple',
            //     fieldSql: ' ',
            //     type: 55,
            //     // // 默认值
            //     // fieldValue: 'sheet_status',
            //     // fieldEnum: [
            //     //     { value: 'sheet_status', label: '故障单', type: 55 },
            //     //     { value: 'supv_sheet_status', label: '督办单', type: 423 },
            //     //     { value: 'subway_sheet_status', label: '高铁单', type: 366 },
            //     // ],
            // },
            {
                key: 'new_sheet_status',
                dataIndex: 'new_sheet_status',
                title: '工单状态',
                valueType: 'newEnumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectSheetStatus',
                type: 55,
                // 默认值
                fieldValue: 'sheet_status',
                fieldEnum: [
                    { value: 'sheet_status', label: '故障单', type: 55 },
                    { value: 'supv_sheet_status', label: '督办单', type: 423 },
                    { value: 'subway_sheet_status', label: '高铁单', type: 366 },
                ],
            },
            // {
            //     key: 'subway_sheet_status',
            //     dataIndex: 'subway_sheet_status',
            //     title: '高铁工单状态',
            //     valueType: 'enumeration',
            //     fieldMode: 'multiple',
            //     fieldSql: 'alarmSearch_selectSheetStatus',
            //     type: 366,
            // },
            // {
            //     key: 'subway_sheet_no',
            //     dataIndex: 'subway_sheet_no',
            //     title: '高铁工单编号',
            //     valueType: 'text',
            //     showOperator: true,
            //     operatorKeys: ['eq', 'like'],
            //     defaultValue: {
            //         operator: 'like',
            //     },
            // },
            // {
            //     key: 'new_sheet_no',
            //     dataIndex: 'new_sheet_no',
            //     title: '工单编号',
            //     valueType: 'text',
            //     showOperator: true,
            //     operatorKeys: ['eq', 'like'],
            //     defaultValue: {
            //         operator: 'like',
            //     },
            //     // 默认值
            //     // fieldValue: 'sheet_no',
            //     // fieldEnum: [
            //     //     { value: 'sheet_no', label: '故障单' },
            //     //     { value: 'supv_sheet_no', label: '督办单' },
            //     //     { value: 'subway_sheet_no', label: '高铁单' },
            //     // ],
            // },
            {
                key: 'new_sheet_no',
                dataIndex: 'new_sheet_no',
                title: '工单编号',
                valueType: 'newText',
                showOperator: false,
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                defaultValue: {
                    operator: 'like',
                },
                // 默认值
                fieldValue: 'sheet_no',
                fieldEnum: [
                    { value: 'sheet_no', label: '故障单' },
                    { value: 'supv_sheet_no', label: '督办单' },
                    { value: 'subway_sheet_no', label: '高铁单' },
                ],
            },
            // {
            //     key: 'sheet_no',
            //     dataIndex: 'sheet_no',
            //     title: '工单编号',
            //     valueType: 'text',
            //     showOperator: true,
            //     operatorKeys: ['eq', 'like'],
            //     defaultValue: {
            //         operator: 'like',
            //     },
            // },
            {
                key: 'org_type',
                dataIndex: 'org_type',
                title: '告警类别',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // fieldSql: 'alarmSearch_selectSendStatus',
                fieldEnum: [
                    { key: '1', value: '设备告警' },
                    { key: '2', value: '性能告警' },
                    { key: '3', value: '巡检告警' },
                    { key: '4', value: 'AI能耗告警' },
                ],
                type: 25,
            },
            {
                key: 'station_info',
                dataIndex: 'station_info',
                title: '专业网管信息',
                valueType: 'text',
                showOperator: true,
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'nms_alarm_id',
                dataIndex: 'nms_alarm_id',
                title: '专业网管ID',
                valueType: 'text',
                showOperator: true,
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'group_id',
                dataIndex: 'group_id',
                title: '网元组ID',
                valueType: 'text',
                showOperator: true,
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'sub_alarm_type',
                dataIndex: 'sub_alarm_type',
                title: '告警子类型',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // fieldSql: 'alarmSearch_selectSendStatus',
                fieldSql: 'alarmSearch_selectSubAlarmType',
                type: 117,
            },
            {
                key: 'ne_ip',
                dataIndex: 'ne_ip',
                title: '网元IP',
                valueType: 'text',
                showOperator: true,
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'is_priority_room',
                dataIndex: 'is_priority_room',
                title: '是否重保机房',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldEnum: [
                    { key: 1, value: '是' },
                    { key: 2, value: '否' },
                    { key: 0, value: '其他' },
                ],
                type: 380,
            },
            {
                key: 'special_field3',
                dataIndex: 'special_field3',
                title: '网络层次',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectSheetStatus',
                type: 95,
            },
            {
                // dataIndex: 'alarm_title',
                key: 'site_name',
                dataIndex: 'site_name',
                title: '局站名称',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                // dataIndex: 'alarm_title',
                key: 'special_field0',
                dataIndex: 'special_field0',
                title: '机房名称',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                // dataIndex: 'alarm_title',
                key: 'alarm_source',
                dataIndex: 'alarm_source',
                title: '告警来源',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'network_type_top',
                dataIndex: 'network_type_top',
                title: '一级网络类型',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldSql: 'alarmSearch_selectNetworkTypeTop',
                type: 228,
            },
            {
                key: 'locate_info',
                dataIndex: 'locate_info',
                title: '定位信息描述',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'is_share',
                dataIndex: 'is_share',
                title: '电联共享标识',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldSql: ' ',
                type: 413,
            },
            {
                key: 'probable_cause',
                dataIndex: 'probable_cause',
                title: '厂家告警号',
                valueType: 'text',
                operatorKeys: ['eq', 'ne'],
                showOperator: true,
                defaultValue: {
                    operator: 'eq',
                },
            },
        ],
        columnsPlatform: [
            {
                key: 'professional_type',
                dataIndex: 'professional_type',
                title: '专业',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // hideInTable: true,
                // fieldSql: 'alarmSearch_selectProfessionalType'
                type: 23,
            },
            {
                key: 'cancel_type',
                dataIndex: 'cancel_type',
                title: '清除类型',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 440,
            },
            {
                key: 'province_region_city',
                dataIndex: 'province_region_city',
                title: '省市区',
                valueType: 'cascader',
                fieldSql: 'alarmSearch_selectProvinceRegionCity',
            },
            {
                key: 'event_time',
                dataIndex: 'event_time',
                title: '首次告警时间',
                valueType: 'dateTimeRange',
                type: 62,
            },
            {
                key: 'cancel_time',
                dataIndex: 'cancel_time',
                title: '清除时间',
                valueType: 'dateTimeRange',
                // defaultValue: {
                //     value: ['yesterday', 'tonight'],
                // },
                type: 69,
            },
            {
                key: 'last_event_time_str',
                dataIndex: 'last_event_time_str',
                title: '末次时间',
                valueType: 'dateTimeRange',
                // defaultValue: {
                //     value: ['yesterday', 'tonight'],
                // },
                type: 425,
            },
            {
                key: 'eqp_object_class',
                dataIndex: 'eqp_object_class',
                title: '设备类型',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                type: 9,
            },
            {
                key: 'eqp_label',
                dataIndex: 'eqp_label',
                title: '告警网元名称',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 7,
            },
            {
                key: 'vendor_severity',
                dataIndex: 'vendor_severity',
                title: '告警级别',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 32,
            },
            {
                key: 'alarm_source',
                dataIndex: 'alarm_source',
                title: '业务系统',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 3,
            },
            {
                key: 'title_text',
                dataIndex: 'title_text',
                title: '告警标题',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 30,
            },
            {
                key: 'alarm_act_count',
                dataIndex: 'alarm_act_count',
                title: '发生次数',
                valueType: 'text',
                operatorKeys: ['eq', 'ne'],
                showOperator: true,
                defaultValue: {
                    operator: 'eq',
                },
                type: 173,
            },
            {
                // dataIndex: 'alarm_title',
                key: 'station_info',
                dataIndex: 'station_info',
                title: '告警来源',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 304,
            },
            {
                key: 'locate_info',
                dataIndex: 'locate_info',
                title: '告警内容',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 15,
            },
            {
                key: 'standard_alarm_id',
                dataIndex: 'standard_alarm_id',
                title: '网管告警ID',
                valueType: 'text',
                operatorKeys: ['eq', 'ne'],
                showOperator: true,
                defaultValue: {
                    operator: 'eq',
                },
                type: 35,
            },
            {
                key: 'nms_name',
                dataIndex: 'nms_name',
                title: '归属地域',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 135,
            },
            {
                key: 'new_send_status',
                dataIndex: 'new_send_status',
                title: '派单状态',
                valueType: 'newEnumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectSendStatus',
                type: 52,
                // 默认值
                fieldValue: 'send_status',
                fieldEnum: [
                    { value: 'send_status', label: '故障单', type: 52 },
                    { value: 'supv_send_status', label: '督办单', type: 424 },
                    { value: 'subway_send_status', label: '高铁单', type: 367 },
                ],
            },
            {
                key: 'new_sheet_status',
                dataIndex: 'new_sheet_status',
                title: '工单状态',
                valueType: 'newEnumeration',
                fieldMode: 'multiple',
                fieldSql: 'alarmSearch_selectSheetStatus',
                type: 55,
                // 默认值
                fieldValue: 'sheet_status',
                fieldEnum: [
                    { value: 'sheet_status', label: '故障单', type: 55 },
                    { value: 'supv_sheet_status', label: '督办单', type: 423 },
                    { value: 'subway_sheet_status', label: '高铁单', type: 366 },
                ],
            },
            {
                key: 'new_sheet_no',
                dataIndex: 'new_sheet_no',
                title: '工单编号',
                valueType: 'newText',
                showOperator: false,
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                defaultValue: {
                    operator: 'like',
                },
                // 默认值
                fieldValue: 'sheet_no',
                fieldEnum: [
                    { value: 'sheet_no', label: '故障单' },
                    { value: 'supv_sheet_no', label: '督办单' },
                    { value: 'subway_sheet_no', label: '高铁单' },
                ],
            },
            {
                key: 'intending_send_time',
                dataIndex: 'intending_send_time',
                title: '派单时间',
                valueType: 'dateTimeRange',
                defaultValue: {
                    value: [],
                },
                type: 154,
            },
            {
                key: 'failed_reason',
                dataIndex: 'failed_reason',
                title: '派单失败原因',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
                type: 54,
            },
        ],
        config: {
            search_span: {
                sm: {
                    with: 1400,
                    span: 8,
                },
                default: 6,
            },
            search_colSize: 1,
        },
    },
    {
        tab: '按过滤器查询',
        key: '2',
        queryType: 'filterId',
        columns: [
            {
                key: 'event_time',
                dataIndex: 'event_time',
                title: '告警发生时间',
                valueType: 'dateTimeRange',
                defaultValue: {
                    value: ['yesterday', 'tonight'],
                },
            },
            {
                key: 'active_status',
                dataIndex: 'active_status',
                title: '告警状态',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldSql: 'alarmSearch_selectAlarmState',
                type: 68,
            },
            {
                key: 'province_region_city',
                dataIndex: 'province_region_city',
                title: '省市区',
                valueType: 'cascader',
                fieldSql: 'alarmSearch_selectProvinceRegionCity',
            },
            {
                key: 'send_status',
                dataIndex: 'send_status',
                title: '派单状态',
                valueType: 'enumeration',
                fieldMode: 'multiple', // 可选，默认null，field select是否为多选模式
                fieldSearch: true,
                fieldSql: 'alarmSearch_selectSendStatus',
                type: 52,
            },
            {
                key: 'filter_type',
                dataIndex: 'filter_type',
                title: '过滤器类型',
                valueType: 'enumeration',
                // fieldSql: 'alarmSearch_selectFilterType',
                fieldEnum: [
                    { key: 'myFilters', value: '我的过滤器' },
                    { key: 'allFilters', value: '全部过滤器' },
                    // { key: 'allRules', value: '派单规则' }
                    // { key: 'ruleFitlers', value: '派单规则' },
                ],
                defaultValue: {
                    value: 'myFilters',
                },
            },
            // 此处 没有数据源，应该是特殊查询
            {
                key: 'filter_id',
                dataIndex: 'filter_id',
                title: '过滤器名称',
                valueType: 'enumeration',
                filterType: 'myFilters',
                fieldSearch: true,
                fieldMode: 'multiple',
                // fieldSql: '',
                // defaultValue: {
                //     value: 1,
                // },
            },

            {
                key: 'eqp_object_class',
                dataIndex: 'eqp_object_class',
                title: '设备类型',
                valueType: 'enumeration',
                fieldMode: 'multiple',
                // fieldSql: 'alarmSearch_selectEqpObjectClass'
                type: 9,
            },
            {
                // dataIndex: 'alarm_title',
                key: 'alarm_title_text',
                dataIndex: 'alarm_title_text',
                title: '告警标题',
                valueType: 'text',
                operatorKeys: ['eq', 'like', 'ne', 'notLike'],
                showOperator: true,
                defaultValue: {
                    operator: 'like',
                },
            },
            {
                key: 'probable_cause',
                dataIndex: 'probable_cause',
                title: '厂家告警号',
                valueType: 'text',
                operatorKeys: ['eq', 'ne'],
                showOperator: true,
                defaultValue: {
                    operator: 'eq',
                },
            },
            // {
            //     key: 'is_undistributed_send_status',
            //     dataIndex: 'is_undistributed_send_status',
            //     title: '是否派单告警',
            //     valueType: 'enumeration',
            //     fieldPlaceholder: '是',
            //     // fieldSql: 'alarmSearch_selectIsUndistributedSendStatus',
            //     fieldEnum: [
            //         { key: -1, value: '是' },
            //         { key: 0, value: '否' },
            //     ],
            // },
            // {
            //     key: 'send_status',
            //     dataIndex: 'send_status',
            //     title: '派单状态',
            //     valueType: 'enumeration',
            //     fieldSearch: true,
            //     fieldSql: 'alarmSearch_selectSendStatus'
            // }
            // {
            //     key: 'alarm_origin',
            //     dataIndex: 'alarm_origin',
            //     title: '关联查询',
            //     valueType: 'enumeration',
            //     fieldSearch: true,
            //     fieldSql: 'alarmSearch_selectAlarmOrigin',
            //     defaultValue: {
            //         value: 0
            //     }
            // }
        ],
        config: {
            search_span: {
                sm: {
                    with: 1400,
                    span: 8,
                },
                default: 6,
            },
            // search_defaultCollapsed: false,
        },
    },
];
const versionTabs = constants.version === 'unicom' ? Tabs_unicom : Tabs;
export default versionTabs;
export { customQuery };
