const fakeData = [
    // {
    //     moduleId: 27,
    //     moduleName: '基本信息',
    //     orderId: 25,
    //     professionalType: null,
    //     professionalTypes: null,
    //     professionalName: null,
    //     professionalNames: null,
    //     optionalFlag: 3,
    //     checked: 1,
    // },
    // {
    //     moduleId: 28,
    //     moduleName: '工作记录',
    //     orderId: 26,
    //     professionalType: null,
    //     professionalTypes: null,
    //     professionalName: null,
    //     professionalNames: null,
    //     optionalFlag: 3,
    //     checked: 1,
    // },
    {
        moduleId: 1,
        moduleName: '网络故障工单',
        orderId: 1,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 3,
        checked: 1,
    },
    {
        moduleId: 2,
        moduleName: '业务故障单',
        orderId: 2,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 3,
        moduleName: '协查单',
        orderId: 3,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 4,
        moduleName: '重保调度单',
        orderId: 4,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 5,
        moduleName: '重保(自查)',
        orderId: 5,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 6,
        moduleName: '重保执行记录',
        orderId: 6,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 7,
        moduleName: '割接调度单',
        orderId: 7,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 0,
    },
    {
        moduleId: 8,
        moduleName: '机房巡视表',
        orderId: 8,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 9,
        moduleName: '上班次遗留问题',
        orderId: 9,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 10,
        moduleName: '上班次重要通知',
        orderId: 10,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 11,
        moduleName: '重大故障情况',
        orderId: 11,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 12,
        moduleName: '重保情况',
        orderId: 12,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 13,
        moduleName: '安全事件记录',
        orderId: 13,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 14,
        moduleName: '网络割接情况',
        orderId: 14,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 15,
        moduleName: '其他',
        orderId: 15,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 16,
        moduleName: '遗留问题',
        orderId: 16,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 1,
        checked: 1,
    },
    {
        moduleId: 17,
        moduleName: '微信群及保障事件',
        orderId: 17,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 18,
        moduleName: '网络安全事件',
        orderId: 18,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 19,
        moduleName: '网络故障（自查）',
        orderId: 19,
        professionalType: null,
        professionalTypes: ['1', '9998', '9999', '9997', '80'],
        professionalNames: null,
        professionalName: ['核心网', 'ATM专业', '互联网专业', '大客户平台专业', 'IT云监控'].join(','),
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 20,
        moduleName: '无线基站大面积断站',
        orderId: 20,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 21,
        moduleName: '日常申告及投诉事件',
        orderId: 21,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 22,
        moduleName: '业务故障(自查)',
        orderId: 22,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 23,
        moduleName: '网络割接(自查)',
        orderId: 22,
        professionalType: null,
        professionalTypes: ['9996', '1', '9999', '9998'],
        professionalNames: null,
        professionalName: ['业务平台专业', '核心网', '互联网专业', 'ATM专业'].join(','),
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 24,
        moduleName: '告警与优化',
        orderId: 23,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 25,
        moduleName: '业务平台监控日报',
        orderId: 29,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    {
        moduleId: 26,
        moduleName: '在线操作',
        orderId: 24,
        professionalType: null,
        professionalTypes: null,
        professionalName: null,
        professionalNames: null,
        optionalFlag: 2,
        checked: 1,
    },
    // {
    //     moduleId: 29,
    //     moduleName: '重要通知',
    //     orderId: 27,
    //     professionalType: null,
    //     professionalTypes: null,
    //     professionalName: null,
    //     professionalNames: null,
    //     optionalFlag: 3,
    //     checked: 1,
    // },
    // {
    //     moduleId: 30,
    //     moduleName: '上传附件',
    //     orderId: 28,
    //     professionalType: null,
    //     professionalTypes: null,
    //     professionalName: null,
    //     professionalNames: null,
    //     optionalFlag: 3,
    //     checked: 1,
    // },
];

export default function selectedModuleByGroupConverter(res) {
    if (res?.code === 200 && Array.isArray(res.data)) {
        const { data } = res;

        return data.map((item) => {
            return {
                ...item,
                label: item.moduleName,
                id: item.moduleId,
                checked: Boolean(item.checked),
                disabled: item.optionalFlag === 0 || item.optionalFlag === 3,
            };
        });
    }

    return [];
}
